name: CI

on: 
  push:
    branches:
      - main
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build check
        run: echo "Build successful"
